[package]
name = "fsh-client"
edition.workspace = true
version.workspace = true

[dependencies]
fsh-types = { workspace = true }
fsh-error = { workspace = true }
fsh-transport = { workspace = true }
fsh-auth = { workspace = true }
fsh-channel = { workspace = true }
fsh-session = { workspace = true }
fsh-agent = { workspace = true }
# asupersync = { workspace = true }  # uncomment when /dp/asupersync available
tokio = { workspace = true }
tracing = { workspace = true }
